version: "3.9"

services:
  legitimate:
    build: ./legitimate
    container_name: banco-legitimo
    ports:
      - "5000:5000"
    networks:
      - demo-net

  phishing:
    build: ./phishing
    container_name: sitio-phishing
    ports:
      - "5001:5001"
    networks:
      - demo-net
    depends_on:
      - legitimate

networks:
  demo-net:
    driver: bridge
