version: "3.9"

services:
  legitimate:
    build: ./legitimate
    container_name: banco-legitimo
    ports:
      - "5000:5000"
    networks:
      - demo-net

  phishing:
    build: ./phishing
    container_name: sitio-phishing
    ports:
      - "5001:5001"
    networks:
      - demo-net
    depends_on:
      - legitimate

  search:
    build: ./search
    container_name: buscador-demo
    ports:
      - "5002:5002"
    networks:
      - demo-net

networks:
  demo-net:
    driver: bridge
